################################################################################
# Some services behind a reverse proxy.
################################################################################
version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro

  # Comment out services you plan to develop locally and edit the
  # default.conf with `docker.host.internal` instead of the
  # service name.
  
  # the swagger ui
  # TODO this repo's tag doesn't seem to match the latest `main` commit
  # houston-api-docs:
  #  image: gcr.io/a2w-staging/houston-api-docs:89a3bb5
  session-api:
    image: gcr.io/a2w-staging/session-api:develop
    environment:
      REDIS_HOST: redis
      PORT: 80
  accounts-receivable-api:
    image: gcr.io/a2w-staging/accounts-receivable-api:develop
    environment:
      REDIS_HOST: redis
      PORT: 80
  customers-api:
    image: gcr.io/a2w-staging/customers-api:develop
    environment:
      REDIS_HOST: redis
      PORT: 80
 
  # graphql-api will stitch together the graphql endpoints for the services
  # defined in its resourceUrls.ts file
  graphql-api:
    image: gcr.io/a2w-staging/graphql-api:develop
    # image: graphql-api:dx-improvements
    environment:
      NODE_ENV: development
  log-receiver:
    image: gcr.io/a2w-staging/log-receiver:develop
    environment:
      PORT: 80
    
  redis:
    image: redis
    # Expose the port to the host machine so that it can be used for local
    # developnment.
    ports:
      - "6379:6379"
  

