################################################################################
# Some services behind a reverse proxy.
################################################################################
version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro

  # Comment out services you plan to develop locally and edit the
  # default.conf with `docker.host.internal` instead of the
  # service name.
  session-api:
    image: gcr.io/a2w-staging/session-api:a6a7de1
    environment:
      REDIS_HOST: redis
  customers-api:
    image: gcr.io/a2w-staging/customers-api:78c9734
    environment:
      REDIS_HOST: redis
  users-api:
    image: gcr.io/a2w-staging/users-api:773de6a
    environment:
      REDIS_HOST: redis
  
  # the swagger ui
  houston-api-docs:
    image: gcr.io/a2w-staging/houston-api-docs:da64030
  redis:
    image: redis
    # Expose the port to the host machine so that it can be used for local
    # developnment.
    ports:
      - "6379:6379"
